In [2]:
#Import Pandas
import pandas as pd
import os

In [3]:
#Read in the dataset
hotel_bookings = pd.read_csv(r'hotel_bookings.csv')

In [5]:
#Look at the dataset
hotel_bookings.shape

(119390, 32)

In [6]:
#Drop/Rename columns
hotel_bookings.columns

Index(['hotel', 'is_canceled', 'lead_time', 'arrival_date_year',
       'arrival_date_month', 'arrival_date_week_number',
       'arrival_date_day_of_month', 'stays_in_weekend_nights',
       'stays_in_week_nights', 'adults', 'children', 'babies', 'meal',
       'country', 'market_segment', 'distribution_channel',
       'is_repeated_guest', 'previous_cancellations',
       'previous_bookings_not_canceled', 'reserved_room_type',
       'assigned_room_type', 'booking_changes', 'deposit_type', 'agent',
       'company', 'days_in_waiting_list', 'customer_type', 'adr',
       'required_car_parking_spaces', 'total_of_special_requests',
       'reservation_status', 'reservation_status_date'],
      dtype='object')

In [ ]:
#hotel_bookings.drop(columns=[''],inplace=True) inplace- drop in this data frame
hotel_bookings.rename({'adults':'num_adults','children':'num_children','babies':'num_babies'}, axis=1,inplace=True)
hotel_bookings.head()

In [ ]:
#NaNs (Not a Number)-- null % of null values
hotel_bookings.isnull().sum() *100 / len(hotel_bookings)

In [19]:
hotel_bookings['agent'].unique()
hotel_bookings[hotel_bookings['agent']==5] #either drop with NaN or fill with -1

#hotel_bookings['agent'].fillna(-1,inplace=True) # fill all Nan with -1
hotel_bookings[hotel_bookings['num_children'].isna()]  # 4 rows so  drop??? these rows
hotel_bookings[hotel_bookings['country'].isna()][['hotel','is_canceled','country']] #subset
hotel_bookings[hotel_bookings['company'].isna()] # drop column

hotel_bookings.dropna(subset=['num_children'],inplace=True) #drop 4 rows 
hotel_bookings.drop(columns=['company'],inplace=True) #drop company column

In [35]:
#Check column Data types
hotel_bookings.dtypes

hotel                               object
is_canceled                        boolean
lead_time                            int64
arrival_date                        object
arrival_date_month                  object
arrival_date_year                   object
arrival_date_week_number             int64
arrival_date_day_of_month            int64
stays_in_weekend_nights              int64
stays_in_week_nights                 int64
num_adults                           int64
num_children                         int64
num_babies                           int64
meal                                object
country                             object
market_segment                      object
distribution_channel                object
is_repeated_guest                  boolean
previous_cancellations               int64
previous_bookings_not_canceled       int64
reserved_room_type                  object
assigned_room_type                  object
booking_changes                      int64
deposit_type                        object
agent                              float64
days_in_waiting_list                 int64
customer_type                       object
adr                                float64
required_car_parking_spaces          int64
total_of_special_requests            int64
reservation_status                  object
reservation_status_date             object
lead_time_binned                  category
dtype: object

In [ ]:
#Changing the datatypes as per values
hotel_bookings = hotel_bookings.astype({'is_canceled':'boolean', 'is_repeated_guest':'boolean','num_children':'int64'})
hotel_bookings.dtypes

In [ ]:
#Bin columns- grouping columns to reduce the values in groups (grouping in rows)
hotel_bookings['lead_time'].unique() #bin to make it range
hotel_bookings['lead_time'].describe()

#define bins and labels
bins = [0,100,200,300,400,500,600,700,800]
labels = ['0-100','101-200','201-300','301-400','401-500','501-600','601-700','701-800']

hotel_bookings['lead_time_binned']= pd.cut(hotel_bookings['lead_time'],bins=bins, labels=labels)
hotel_bookings[['lead_time','lead_time_binned']]

In [ ]:
#Separate columns- split arrival_date for month
# ading arrival_date column for demonstrating separate columns
#hotel_bookings['arrival_date'] = 'July-2015'
hotel_bookings.insert(loc=3, column='arrival_date', value='July-2015') 
hotel_bookings['arrival_date'] = pd.to_datetime(hotel_bookings['arrival_date'])
hotel_bookings['arrival_date_month']= hotel_bookings['arrival_date'].str.split('-', expand=True)[0]
hotel_bookings['arrival_date_year'] = hotel_bookings['arrival_date'].str.split('-', expand=True)[1]

#move columns - pop column and then insert at the desired location in the file
#column1_to_move = hotel_bookings.pop('arrival_date')
column2_to_move = hotel_bookings.pop('arrival_date_month')
column3_to_move = hotel_bookings.pop('arrival_date_year')

#hotel_bookings.insert(3,'arrival_date',column1_to_move)
hotel_bookings.insert(4,'arrival_date_month',column2_to_move)
hotel_bookings.insert(5,'arrival_date_year',column3_to_move)

#drop arrival_date

In [ ]:
#string cleaning, any special characters at the end of hotel name etc
hotel_bookings['hotel'].unique()

array(['Resort Hotel', 'City Hotel'], dtype=object)

In [ ]:
#string cleaning using Regex
hotel_bookings['hotel'] =hotel_bookings['hotel'].replace(r"[\#\*\n\^]",'', regex=True)

In [ ]:
#Remove duplicates, 
#find duplicate rows
hotel_bookings.duplicated(keep=False)
hotel_bookings.loc[hotel_bookings.duplicated(keep=False)]
# keep first instance of the row and remove the second
hotel_bookings.drop_duplicates(keep='first',inplace=False)

In [44]:
hotel_bookings.loc[hotel_bookings.duplicated(keep=False)]

,hotel,is_canceled,lead_time,arrival_date,arrival_date_month,arrival_date_year,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,...,deposit_type,agent,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date,lead_time_binned
4,Resort Hotel,False,14,July-2015,July,2015,27,1,0,2,...,No Deposit,240.0,0,Transient,98.00,0,1,Check-Out,2015-07-03,0-100
5,Resort Hotel,False,14,July-2015,July,2015,27,1,0,2,...,No Deposit,240.0,0,Transient,98.00,0,1,Check-Out,2015-07-03,0-100
21,Resort Hotel,False,72,July-2015,July,2015,27,1,2,4,...,No Deposit,250.0,0,Transient,84.67,0,1,Check-Out,2015-07-07,0-100
22,Resort Hotel,False,72,July-2015,July,2015,27,1,2,4,...,No Deposit,250.0,0,Transient,84.67,0,1,Check-Out,2015-07-07,0-100
39,Resort Hotel,False,70,July-2015,July,2015,27,2,2,3,...,No Deposit,250.0,0,Transient,137.00,0,1,Check-Out,2015-07-07,0-100
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119352,City Hotel,False,63,July-2015,July,2015,35,31,0,3,...,No Deposit,9.0,0,Transient-Party,195.33,0,2,Check-Out,2017-09-03,0-100
119353,City Hotel,False,63,July-2015,July,2015,35,31,0,3,...,No Deposit,9.0,0,Transient-Party,195.33,0,2,Check-Out,2017-09-03,0-100
119354,City Hotel,False,63,July-2015,July,2015,35,31,0,3,...,No Deposit,9.0,0,Transient-Party,195.33,0,2,Check-Out,2017-09-03,0-100
119372,City Hotel,False,175,July-2015,July,2015,35,31,1,3,...,No Deposit,42.0,0,Transient,82.35,0,1,Check-Out,2017-09-04,101-200
119373,City Hotel,False,175,July-2015,July,2015,35,31,1,3,...,No Deposit,42.0,0,Transient,82.35,0,1,Check-Out,2017-09-04,101-200